name: "Pull Request Labeller"
on:
  - pull_request_target

jobs:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
